org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.12
forge_version_range=[47.3.12,48)
loader_version_range=[47,48)
mapping_channel=official
mapping_version=1.20.1

mc_version=1.20.1
jei_version=15.3.0.4
nstut_lib_version=dcb077ec173ed7cc4ddbbd1a9b57ba287e077a91

## Mod Properties
mod_id=biotech
mod_name=Biotech
mod_license=All Rights Reserved
mod_version=2.1
mod_group_id=com.nstut.biotech
mod_authors=NsTut
mod_description=The mod that lets you biologically engineer Minecraft.
