org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version_1_20_1=1.20.1
minecraft_version_range_1_20_1=[1.20.1,1.21)
forge_version_1_20_1=47.3.12
forge_version_range_1_20_1=[47.3.12,48)
forge_loader_range_1_20_1=[47,48)
jei_version_1_20_1=15.3.0.4
patchouli_file_1_20_1=4966125

minecraft_version_1_21_1=1.21.1
minecraft_version_range_1_21_1=[1.21.1,1.22)
neoforge_version_1_21_1=21.1.201
jei_version_1_21_1=19.43.0.392
patchouli_file_1_21_1=7730942

minecraft_version_26_1_2=26.1.2
minecraft_version_range_26_1_2=[26.1.2,26.2)
neoforge_version_26_1_2=26.1.2.76
jei_version_26_1_2=29.29.0.86
patchouli_file_26_1_2=8404543

nstut_lib_version=0.8
nstut_lib_ref=611023e4f9833128f4019ad6ef9192a68ed7be35
lombok_version=1.18.48

mod_id=biotech
mod_name=Biotech
mod_license=All Rights Reserved
mod_version=2.1
mod_group_id=com.nstut.biotech
mod_authors=NsTut
mod_description=The mod that lets you biologically engineer Minecraft.
