modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/UpperMoon0/Biotech/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/biotech"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "patchouli"
type = "required"
versionRange = "${patchouli_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "nstutlib"
type = "required"
versionRange = "[0.8.1,0.9)"
ordering = "AFTER"
side = "BOTH"
